#!/bin/bash
val=0
str=""
echo "size  speed sn"
/usr/sbin/dmidecode -t memory  | while read line
do
        if [ -z "$line" ]
        then
                continue
        fi
        res=`echo $line | grep -E "Size|Speed|Serial" | awk -F ':' '{print$2}'| awk '{print$1}'`
        str="$str $res"
        if ! [ -z "$res" ]
        then
                val=`expr $val + 1`
                if [ $val -ge 3 ]
                then
                        echo $str
                        val=0
                        str=""
                fi
        fi

done
