#!/bin/bash
#conf=yumserver.ini
#added aliyun for new yum by jigang@2012-06-12
conf=/etc/gemstonehints
logfile=/tmp/gerepo.log
repo_name="ops"
repo_dir=/etc/yum.repos.d

function log_msg ()
{
	tt=`date "+%Y-%m-%d %H:%M:%S"`
	pid=`echo $$`
	echo -n "$tt " >> $logfile
	for i in "$@"; do
        	echo -n $i >>$logfile
	done
	echo "" >> $logfile

}

function check_conf ()
{
	if ! [ -f "$conf" ]
	then
		bname=`basename $conf`
		echo "yumcm3=yum.cm3.tbsite.net" > "/tmp/$bname.tmp"
		echo "yumcm4=yum.cm4.tbsite.net" >> "/tmp/$bname.tmp"
		echo "yumcm5=yum.cm5.tbsite.net" >> "/tmp/$bname.tmp"
		echo "yumcm6=yum.cm6.tbsite.net" >> "/tmp/$bname.tmp"
		echo "yumcm8=yum.cm8.tbsite.net" >> "/tmp/$bname.tmp"
		echo "yumcnz=yum.cnz.alimama.com" >> "/tmp/$bname.tmp"		
	else
		echo "ok"
	fi
}

function get_yumserver ()
{
        res=`hostname | grep alimama`
        if [ -z "$res" ]
        then
                num=`hostname |sed 's/\.tbsite\.net//g'| awk -F . '{print$NF}'`
                cat "$conf" | grep -v '^#' | grep "yum$num"  | awk -F '=' '{print$2}'
        else
                cat "$conf" | grep -v '^#' | grep "yumcnz" | awk -F '=' '{print$2}'
        fi
}
function get_release_r()
{
	if  [ -f "/etc/redhat-release" ]
	then
   		a=`cat /etc/redhat-release | awk '{print$7}' | awk '{a=index($1, ".");if(a>0)print substr($1,0,a-1);else print$1}'`
   		echo $a
	fi
}
function is_x86_64 ()
{
	a=`uname -a | grep x86_64`
	if [ -z "$a" ]
	then
		echo "i386"
	else
		echo "x86_64"
	fi	
}
function ge_repo_taobao
{
	name=$1
 	server=$2
	re=$3
	arch=$4
	##############
	echo "[$repo_name.$re.$arch]"
	echo "name=$repo_name.$re.$arch"
	#echo "baseurl=http://$server/$repo_name/\$releasever/$arch"
	echo "baseurl=http://$server/$repo_name/$re/$arch"
	echo "gpgcheck=0"
}	

function ge_repo_aliyun
{
	name=$1
 	server=$2
	re=$3
	arch=$4
	##############
	echo "[apsara]"
	echo "name=Package for Apsara"
	echo "baseurl=http://$server/aliyun/apsara/\$releasever/\$basearch/apsara"
	echo "gpgcheck=0"
	echo "enabled=1"

	echo "[extras]"
	echo "name=Extra Packages for Enterprise Linux $arch - \$basearch"
	echo "baseurl=http://$server/aliyun/extras/\$releasever/\$basearch"
	echo "enabled=1"
	echo "gpgcheck=0"
	echo "gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL"
	echo ""
}

function main ()
{
	if [ -z "`check_conf`" ]
	then
		conf="/tmp/`basename $conf`.tmp"
	fi


	server=`get_yumserver`
	if [ -z "$server" ]
	then
		log_msg "get yum server of `hostname` failed"
		exit 1
	fi

	re=`get_release_r`

	if [ -z "$re" ]
	then
		log_msg "get release of `hostname` failed"
		exit 1
	fi

	arch=`is_x86_64`

	if [ -z "$arch" ]
	then
		log_msg "get arch server of `hostname` failed"
		exit 1
	fi

	if [ "$repo_name" == "aliyun" ]
	then
		ge_repo_aliyun $repo_name $server $re $arch > "/tmp/$repo_name.repo"
	else
		ge_repo_taobao $repo_name $server $re $arch > "/tmp/$repo_name.repo"
		ge_repo_taobao $repo_name $server $re "noarch" >> "/tmp/$repo_name.repo"
	fi
	#try to backup original repo file
	if [ -f "$repo_dir/$repo_name.repo" ]
	then
		if ! [ -f "$repo_dir/$repo_name.repo.back" ]
		then
			mv "$repo_dir/$repo_name.repo" "$repo_dir/$repo_name.repo.back"
		fi
	fi
	if [ -f  "/tmp/$repo_name.repo" ]
	then
		cat "/tmp/$repo_name.repo" > "$repo_dir/$repo_name.repo"
	fi
	unlink "/tmp/$repo_name.repo"
}
################

if [ $# -ne 1 ]
	then
		echo "usage: `basename $0` repo_name"
		exit 1
	fi
repo_name=$1
if [ "$repo_name" != "ops" ]
then
	if [ "$repo_name" != "alibase" ]
	then
		if [ "$repo_name" != "aliyun" ]
		then
			echo "usage:`basename $0` ops|alibase|aliyun"
			exit 1
		fi
	fi
fi
main

