#!/bin/bash
function get_subtask ()
{
	ps -Ao pid,ppid | grep $1 | while read pid ppid
	do
		if [ $1 -eq $ppid ]
			then
				echo $pid		
			break;
		fi
	done
}
function conxion ( )
{
	netstat -atpn | grep cmos  | awk '{print $5" "$6" "$7}' | awk -F '/' '{print$1" "$2}' | while read addr status pid name
	do
		tm=`ps -p $pid -o "%C %x %t" | awk '{if(NR>1)print$1" "$2" "$3}'`
		sub=`get_subtask $pid`
		det=""
		if ! [ -z "$sub" ]
		then 
			det=`ps -p  $sub -o start_time,cmd  | awk '{if(NR>1)print$0}'`
		fi
		printf "%s %-10s %-23s %3s " $name $pid $addr $status
		echo "$tm $det"
	done
} 
tm=`date "+%Y-%m-%d %H:%M:%S"`
echo $tm
conxion


