#!/bin/bash

TMP="/tmp/rpm_check.txt"
STR="futex"
#STR="epoll_wait"
TMPDIR="/tmp/rpmdb_back/$$.db"


if ! [ -f "/usr/bin/cmos-timeout" ]
then
	echo "tops-cmos is needed to run timed-run"
	exit 1
fi 

if [ "$1" != "check" ]
then
	if [ "$1" != "fix" ]
	then
		echo "usage:`basename $0` check | fix"
		exit 1
	fi
fi
TYPE=$1


#check whether the rpm db is corrupted
function rpm_block()
{
	num=`ps -A | grep -E "rpm|rpmq" | wc -l`
	if [ $num -eq 0 ]
	then
		echo "no"
		return
	fi
	
	pid=`ps -A | grep "rpmq" | head -n 1 | awk '{print $1}'`
	if  [ -z "$pid" ]
	then
		################added by jigang.djg@2012-05-07 --start
		pid=`ps -A | grep "rpm" | head -n 1 | awk '{print $1}'`	
		if [ -z "$pid" ]
		then
			echo "no"
			return
		fi
		################added by jigang.djg@2012-05-07 --finish
	fi

	/usr/bin/cmos-timeout 3  /usr/bin/strace -p $pid -o $TMP > /dev/null	
	#echo "111111111111111111111"
	if ! [ -f "$TMP" ]
	then
		echo "no"
		return
	fi
	
	num=`grep "$STR" $TMP | wc -l`	
	if [ $num -eq 0 ]
	then
		echo "no"
		return 
	fi
	echo "yes"
}

function kill_block_task()
{
	num=`ps -A | grep yum | wc -l`
	if [ $num -ge 1 ]
	then
		killall -9 yum
	fi

	num=`ps -A | grep rpmq | wc -l`
	if [ $num -ge 1 ]
	then
		killall -9 rpmq
	fi

	num=`ps -A | grep rpm | wc -l`
	if [ $num -ge 1 ]
	then
		killall -9 rpm
	fi


}

function rpm_fix()
{
	if ! [ -d "$TMPDIR" ]
	then
		mkdir -p $TMPDIR >/dev/null
	fi
	mv  /var/lib/rpm/__db*	"$TMPDIR/"
	#rpm --rebuilddb
}

function rpmfix ()
{
	ret=`rpm_block`
	if  [ "$ret" == "yes" ]
	then
		kill_block_task
		rpm_fix
		ret1=`rpm_block`
	fi
	echo "success"
}

function rpmcheck ()
{
	ret=`rpm_block`
	if  [ "$ret" == "yes" ]
	then
		echo "blocked"
	else
		echo "ok"
	fi

}

if [ "$TYPE" == "fix" ]
then
	rpmfix
else
	rpmcheck
fi

if [ -f "$TMP" ]
then
	unlink $TMP
fi

