default:
  buildprefix: '/usr/local'
  prefix: '/'
  perl: '/usr/bin/perl'
  version: '0.0001'
  shebangmunge: 1
  os_specific: no
  xfercmd: '/usr/bin/curl -s -o %s %u'

rpm:
  autoreqprov: no
  epoch: 20

