#!/bin/bash
conf="/etc/yumclone.conf"
source "$conf"
EXE="/usr/bin/rsync"
LOGDIR="/usr/local/yumclone/log"
exec 2>&1
function log_msg ()
{
	logfile="$LOGDIR/yumclone_`date +%Y%m%d`.log"
        tt=`date '+%Y:%m:%d %H:%M:%S'`
        #echo -e "$tt $@\n" >> $logfile
        echo  "$tt $@"
}

function init_yum_clone()
{
	if ! [ -d "$destdir" ]
	then
		log_msg "can not found destdir,just create it:[$destdir]"
		mkdir -pv $destdir
	fi

	if ! [ -f "$EXE" ]
	then
		log_msg "can not found [$EXE]"
		exit 0
	fi
}

function sync_repos()
{
	echo "$modules" | awk -F ',' '{for(i=1;i<=NF;i++){print $i}}' | while read name
	do
		echo "sync:$name"
		log_msg "start sync repo $name"
        	#if ! [ -z "$exclude" ]
        	#then
            	#	exstr=`echo $exclude | awk -F ',' '{for(i=1;i<=NF;i++)printf(" --exclude %s", $i)}'`
        	#fi
        	echo "$EXE --delete-after --contimeout 10 --port $server_port --bwlimit=$download_limit  -az   $master_server::$name $destdir/$name"
        	$EXE --delete-after  --contimeout 10 --port $server_port --bwlimit=$download_limit  -az   $master_server::$name "$destdir/$name"
		log_msg "finish sync repo $name"
		sleep 2
	done
} 

function main ()
{
	if [ "$run" == "yes" ]
	then
		init_yum_clone
	fi
	while true 
	do
		if [ "$run" != "yes" ]
		then
			echo "configured not to run in file [$conf]"
			sleep 30
			continue
		fi
		log_msg "start sync..."
		sync_repos
		echo "sleep for $interval second(s).."
		sleep $interval
	done
}

main
